services:
  # Aplicación Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empleabilidad_app
    restart: always
    ports:
      - "3009:3000"
    environment:
      # Variables de base de datos (AWS RDS) - Credenciales corregidas
      DATABASE_URL: mysql://empleabilidad_user:Sp69jFYU3038@proyecto-formulario.ckiahkstouyr.us-east-1.rds.amazonaws.com:3306/empleabilidad_ucv
      
      # Variables de autenticación
      AUTH_SECRET: 3lGSJ5ZQx4QQSyHwRJxZhN8T6xbUZO0QGrPjSGnBEE8=
      
      # Variable de entorno para producción
      NODE_ENV: production
    volumes:
      # Opcional: para logs persistentes
      - app_logs:/app/logs

volumes:
  app_logs: